#!/bin/bash

set -x
REPO_PATH=$(git rev-parse --show-toplevel)
IMG=andresdemski/spl2019:revealmd
CMD="reveal-md presentacion/cocotb.md --css presentacion/cocotb.css --static presentacion/static"
DOCKER_CMD="docker run --rm -it -v $REPO_PATH:$REPO_PATH -w $REPO_PATH -u$(id -u):$(id -g)"

$DOCKER_CMD $IMG $CMD
